security:
    jwt:
        expiration: 900000.0
        refreshExpirationMs: 604800000
        secret-key: YOUR_KEY
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: YOUR_KEY
        url: jdbc:mysql://localhost:3306/security_practice?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
        username: root
